### ISSUE TITLE
After selecting an item, the keyboard automatically switches to English

### ISSUE THREAD

**Issue by scriptBoris** [dotMorten/XamarinFormsControls#57]
After selecting an item, the keyboard automatically switches to English

I use RU and EN

**Comment by dotMorten** [comment]
@scriptBoris Which platform are you using? Can you provide a sample app that demonstrates the problem and the detailed steps to reproduce? (preferably a screen recording)
AFAIK there's nothing this control can do to cause a keyboard language change.

**Comment by scriptBoris** [comment]
Anroid, no more time

**Comment by ta-yamaoka** [comment]
@scriptBoris 
Since TextView.InputType is restricted, keyboard switching may not be possible depending on the type of IME.
https://github.com/dotMorten/XamarinFormsControls/blob/master/AutoSuggestBox/Platform/NativeAutoSuggestBox.Android.cs#L31

Use a custom render and override the method as shown below.

```c#
protected override AndroidAutoSuggestBox CreateNativeControl()
{
    var control = base.CreateNativeControl();
    if (!control.InputType.HasFlag(InputTypes.ClassText))
    {
        control.SetRawInputType(InputTypes.ClassText);
    }
    return control;
}
```
